name: On Push Publish DNS to Hetzner

on:
  push:
    branches:
      - 'main'

jobs:
  test-error:
      name: Test-Error
      runs-on: ubuntu-latest
      steps:
        - name: Run error
          continue-on-error: true
          run: |
            ./.github/scripts/error.sh
          shell: sh

